/*
    KF2Calc
    ToDoList
    WPressSolutions
    PrevPortfolio2
    BootStrapPortfolio
    PongReplica
    Chartjs
    AjaxwithFetch
    FlexPane
    CanvasColor
    ProjectArchives
    MatrixNumberFall
    Css3Clock
    BulmaCssTester
    CssVariables
    CommonResources

       <Card
          // projectTitle={imageSet}
          // projectTags={imageSet}
          // backSummary={imageSet}
          // frontSummary={imageSet}
          // liveSiteHref={imageSet}
          // caption={imageSet}
          // imgLinkThmb={imageSet}
          // imgLink={imageSet}
          // altTxt={imageSet}
          // imageSet={imageSet}
          // caption2={imageSet}

          />



  imgLinkThmb
        <LiBoxThmb
          imgLinkThumb = {this.props.thumbnail}
          imgLink  = {this.props.link}
          altTxt = {this.props.altTxt}
          imageSet = {this.props.imageSet}
          caption = {this.props.captionText}  
          />
        <LiBoxNoThmb 
          imgLink = {this.props.link}
          imageSet = {this.props.imageSet}  
          />

*/

console.log(Object.keys(data.propData));

const {
  KF2Calc,
  ToDoList,
  WPressSolutions,
  PrevPortfolio2,
  BootStrapPortfolio,
  PongReplica,
  Chartjs,
  AjaxwithFetch,
  FlexPane,
  CanvasColor,
  ProjectArchives,
  MatrixNumberFall,
  Css3Clock,
  BulmaCssTester,
  CssVariables,
  CommonResources,
  HomePageApp,
  DimenciaPortfolio
} = data.propData
